1704470612841	Sync.LogManager	DEBUG	Flushing file log
1704470612844	Sync.LogManager	DEBUG	Log cleanup threshold time: 1703606612844
1704470612847	Sync.LogManager	DEBUG	Done deleting files.
1704470625662	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write or a score bump
1704470630290	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write or a score bump
1704470630293	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write - bumping score
1704471155913	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write or a score bump
1704471169784	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write - bumping score
1704471169789	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write or a score bump
1704471169844	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write or a score bump
1704471187856	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write or a score bump
1704471187942	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write or a score bump
1704471197883	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write or a score bump
1704471199816	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write or a score bump
1704471213514	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write or a score bump
1704471237757	Sync.Engine.Tabs.Tracker	DEBUG	Detected a tab change, but conditions aren't met for a quick write or a score bump
1704471520518	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1704471520663	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1704471520663	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1704471520666	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1704471538922	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1704471539721	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1704471539722	Sync.Service	DEBUG	User-Agent: Firefox/121.0 (Intel Mac OS X 10.15) FxSync/1.123.0.20231211174248.desktop
1704471539722	Sync.Service	INFO	Starting sync at 2024-01-05 16:18:59 in browser session ip-QsKJ4ObdU
1704471539723	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1704471539727	Sync.Status	INFO	Resetting Status.
1704471539728	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1704471539728	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1704471539728	FirefoxAccounts	DEBUG	getOAuthToken enter
1704471539729	FirefoxAccounts	TRACE	getCachedToken returning cached token
1704471539729	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1704471539730	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1704471539761	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1704471539761	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 479\"  data: no]"}
1704471539761	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/197306892/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1704471539761	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1704471539761	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1704471539761	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1704471539761	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1704471539762	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
